# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpcProcessingAlgs
                                 A QGIS plugin
 Processing algorithms for SPC
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-09-14
        copyright            : (C) 2018 by Olivier Dalang / SPC
        email                : olivier.dalang@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Olivier Dalang / SPC'
__date__ = '2018-09-14'
__copyright__ = '(C) 2018 by Olivier Dalang / SPC'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SpcProcessingAlgs class from file SpcProcessingAlgs.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .spc_proc_alg import SpcProcessingAlgsPlugin
    return SpcProcessingAlgsPlugin()
